---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-control-plane
  namespace: kong-ee
  labels:
    app: postgres-control-plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
